apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: check-resource-limits
      match:
        any:
        - resources:
            kinds: ["Pod"]
      exclude:
        any:
        - resources:
            namespaces: ["kube-system", "argocd", "crossplane-system","sonarqube"]
        - resources:
            kinds: ["Pod"]
            selector:
              matchLabels:
                app: sonarqube
      validate:
        message: "Both CPU and memory limits must be set on all containers"
        pattern:
          spec:
            containers:
            - name: "*"
              resources:
                limits:
                  cpu: "?*"
                  memory: "?*"